# Generated by Django 5.0.6 on 2024-06-07 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minilibraries', '0002_library_remove_book_idbn_book_isbn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='libraries',
        ),
    ]
