# Generated by Django 5.0.6 on 2024-06-17 00:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minilibraries', '0006_library_members_delete_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='members',
            field=models.ManyToManyField(related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
