# Generated by Django 5.0.6 on 2024-06-17 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minilibraries', '0007_alter_library_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_returned',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 3, 8, 25, 216281)),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
