# Generated by Django 5.0.6 on 2024-07-06 19:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minilibraries', '0008_book_last_returned_alter_book_date_added'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrower',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_returned',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 19, 13, 51, 139099)),
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('key', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minilibraries.library')),
            ],
        ),
    ]
