# Generated by Django 5.0.6 on 2024-07-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minilibraries', '0010_alter_library_options_invite_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='last_returned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
