# Generated by Django 5.0.6 on 2024-08-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minilibraries', '0011_alter_book_last_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='key',
            field=models.SlugField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
